print('/ :'+str(ord('/'))+ 'bin :'+bin(ord('/')))
print('+ :'+str(ord('+'))+ 'bin :'+bin(ord('+')))
print('* :'+str(ord('*'))+ 'bin :'+bin(ord('*')))
print('- :'+str(ord('-'))+ 'bin :'+bin(ord('-')))
print('= :'+str(ord('='))+ 'bin :'+bin(ord('=')))